Repository Prakharsharma2206/Hacktober22, pull requests merged in 2022-10, with the labels that each got.

#3 Updated App.js
  src/App.js
Labels: HACKTOBERFEST-ACCEPTED

#4 Changing the link
  src/App.js
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#5 added_tiansing_card
  public/Images/tiansing.jpg
  src/App.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#10 given styling to the cards
  src/App.css
  src/App.js
  src/index.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#13 Aligned and imporved card css fixes #11
  package-lock.json
  package.json
  public/Images/Siddhant.jpg
  src/App.css
  src/App.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#16 added new card
  public/Images/akash.jpg
  src/App.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#23 add_yuval
  public/Images/Yuval.jpg
  src/profiles.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#22 add _shubh card
  public/Images/shubh.jpg
  src/profiles.js
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED
